background            #1E1A2B
foreground            #a9fcaa
cursor                #abf995
selection_background  #d453e0
color0                #68e8e3
color8                #7991fc
color1                #8658fc
color9                #cf2062
color2                #cb58fc
color10               #a9d4fc
color3                #ce58a1
color11               #65f957
color4                #57f9ef
color12               #40a4cf
color5                #b7077e
color13               #f02aae
color6                #8f28ef
color14               #28ef75
color7                #b8f2f0
color15               #f4a6cb
