#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a mpv \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+2760+1040
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+2760+1040
bspc rule -a Alacritty:progterm state=floating sticky=on

#AutoStart  applications
sxhkd &
picom --config $HOME/.config/picom.conf &
nitrogen --restore &
dunst &
polybar &
nmcli dev wifi connect <AKHGastzugang> password <Willkommen2021> &

